# For more details please visit the github page (https://github.com/Pequla/MinecraftBot)
token: bot-token-goes-here
command-prefix: !
id:
  discord-server: discord-server-id
  admin-role: role-id
  death-channel: channel-id
  join-leave-channel: channel-id
